# Generated by Django 5.2.8 on 2026-04-23 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_calon', models.CharField(max_length=100)),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
                ('periode', models.CharField(max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='calon/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pemilih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=15, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('sudah_memilih', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilihan', models.CharField(choices=[('calon', 'Memilih Calon'), ('abstain', 'Abstain')], max_length=10)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('calon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pemilwa.calon')),
                ('pemilih', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pemilwa.pemilih')),
            ],
        ),
    ]
