# Generated by Django 6.0.2 on 2026-04-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemilwa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calon',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='calon',
            name='periode',
        ),
    ]
